from classlib import *


SHU=school()
SHU.regSchool()
SHU.add_teacher('韩越兴')
SHU.add_teacher('李青')
# SHU.get_teacher_list()
SHU.add_course("python",'韩越兴')
SHU.add_course("java",'李青')
SHU.add_course('C++','李青')
SHU.add_course('Linux','bug')
SHU.add_student()
SHU.add_student_details('jack','SHU','1231231')
SHU.add_student_details('mike','SHU','3123123')
SHU.get_school_name()
SHU.get_school_address()
SHU.get_teacher_list()
SHU.get_course_list()
SHU.get_student_list()
# SHU.get_school_name()
# SHU.get_school_address()
# SHU.get_student_list()
# stu1=student()
# stu1.signup()
